spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: always
    url: jdbc:mariadb://localhost:3306/library
    username: nathangift
    password: password
  jpa:
    generateDdl: true
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
